# @apiPort = {{$processEnv API_PORT}}
@apiPort = 3001
@apiUrl = localhost
@apiProtocol = https
@host = {{apiProtocol}}://{{apiUrl}}:{{apiPort}}
@apiPath = /api/category
### POST new Category Candidato
#

POST {{host}}{{apiPath}} HTTP/1.1
Content-Type: application/json

{
    "value": "Candidato"
}

### POST new Category Anunciante

POST {{host}}{{apiPath}} HTTP/1.1
Content-Type: application/json

{
    "value": "Anunciante"
}

### POST new Category Admin

POST {{host}}{{apiPath}} HTTP/1.1
Content-Type: application/json

{
    "value": "Admin"
}

