version: '3.9'
services:
  backend:
    container_name: api
    build: .
    ports:
      - 8000:3001
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - NODE_ENV=development
      - DEBUG=1

  db:
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_DB=99Emprega
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - .db:/var/lib/postgres
    ports:
      - 15432:5432
