version: '3.9'
services:
  backend:
    container_name: api
    build: .
    ports:
      - 8000:3001
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - NODE_ENV=development
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=emprega-99-dev.cbuaoiimmoy2.sa-east-1.rds.amazonaws.com
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=99Emprega777
      - POSTGRES_DB=emprega99
      - TYPEORM_AUTO_LOAD_ENTITIES=true
      - TYPEORM_SYNCHRONIZE=true
      # - TYPEORM_CONNECTION=postgres
      # - TYPEORM_ENTITIES=src/infra/typeorm/entities/*.ts
      # - TYPEORM_MIGRATIONS=src/infra/typeorm/migrations/*.ts
      # - TYPEORM_MIGRATIONS_DIR=src/infra/typeorm/migrations
    dns:
      - 8.8.8.8
      - 8.8.4.4

  db:
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_DB=emprega99
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - .db:/var/lib/postgres
    ports:
      - 15432:5432
