POST http://localhost:8000/api/auth/admin/register
Content-Type: application/json

{
    "first_name":"a",
    "last_name":"a",
    "email": "a@gmail.com",
    "password": "a",
    "password_confirm": "a"
}