POST http://localhost:8000/api/auth/signin HTTP/1.1
Content-Type: application/json

{
    "email":"a@gmail.com",
    "password":"a"    
}

###
GET http://localhost:8000/api/auth/user HTTP/1.1
Content-Type: application/json

###

POST http://localhost:8000/api/auth/signout 
Content-Type: application/json


### pessoa juridica anunciante

POST http://localhost:8000/api/auth/register HTTP/1.1
Content-Type: application/json

{
    "first_name":"Ambicioso",
    "last_name":"Anunciante Amb",
    "email": "amb2@gmail.com",
    "password": "@Teste123",
    "password_confirm": "@Teste123",
    "address": "Rua alguma",
    "personCNPJ": "32.305.697/0001-03",
    "phone_number": "12345678900",
    "category":"Anunciante",
    "personType": "Jurídica",
    "tradingNamePerson": "Empresa Do Baralho",
    "companyNamePerson": "Empresa Da Incrivel",
    "stateInscrPerson":"633.488.055.573"
}

### pessoa fisica anunciante com empresa a parte

POST http://localhost:8000/api/auth/register HTTP/1.1
Content-Type: application/json

{
    "first_name":"Mariana",
    "last_name":"Costa Lima",
    "email": "mariana.costa@dominio.com.br",
    "password": "M@riana2023",
    "password_confirm": "M@riana2023",
    "address": "Av. Paulista, 1578, São Paulo, SP",
    "cpf": "123.456.789-09",
    "phone_number": "11999887766",
    "category":"Anunciante",
    "personType": "Física",
    "tradingName": "Vendas Top",
    "companyName": "Top Vendas Comercial Ltda.",
    "stateInscr": "987.654.321.000",
    "cnpj": "12.345.678/0001-99",
    "logo": "logo_top_vendas.png"
}


###

GET http://localhost:8000/api/users?page=1&limit=10 HTTP/1.1

Content-Type: application/json


