POST http://localhost:8000/api/auth/signin HTTP/1.1
Content-Type: application/json

{
    "email":"a@gmail.com",
    "password":"a"    
}

###
GET http://localhost:8000/api/auth/user HTTP/1.1
Content-Type: application/json

###

POST http://localhost:8000/api/auth/signout 
Content-Type: application/json

### register a user with a person and category together

POST http://localhost:8000/api/auth/register HTTP/1.1
Content-Type: application/json

{
    "first_name":"Teste 9",
    "last_name":"Testes teste",
    "email": "teste91852348382938412@gmail.com",
    "password": "@Teste321",
    "password_confirm": "@Teste321",
    "address": "Rua teste",
    "cpf": "12345678900",
    "phone_number": "12345678900",
    "category":"Candidato"

}

###

GET http://localhost:8000/api/users?page=1&limit=100 HTTP/1.1

Content-Type: application/json


