### Create Job Opportunity

POST http://localhost:8000/api/job-opportunity HTTP/1.1
Content-Type: application/json

{
    "companyId": "00b1b1d6-45bf-4f33-8e64-49e4e8cd5593",
    "title": "Vaga Google Staff Engineer",
    "description": "Vaga boa para quem é bom",
    "requirements": "Requesitos Mínimos",
    "salary": 50000,
    "location": "Minas Gegrain",
    "benefits": "Alguns beneficios",
    "salaryRange": { "min": 40, "max": 50},
    "salaryToBeAgreed": false,
    "model": "on_site",
    "isActive": true
}

### Apply to Job Opportunity

POST http://localhost:8000/api/job-opportunity/75ddc64e-3001-4f96-8d7a-886c39062143/apply HTTP/1.1
Content-Type: application/json

{
    "userId": "e47539f9-78f7-46ed-bc6f-9fd1421beaa8"
}


### Get Job Opportunities with Pagination

GET http://localhost:8000/api/job-opportunity?page=1&limit=10 HTTP/1.1
Content-Type: application/json

